CONFIG = {
    'OLLAMA_MODELS': {
        'CLASSIFIER_ABSTRACT_MODEL': "deepseek-r1:32b",
        # 'TEXT_CORRECTION_MODEL': "mistral:7b-instruct-v0.3-fp16",
        'DATASET_GENERATION': "mistral-small:22b",
        'REWRITE_QUERY_MODEL': "meta-llama/Llama-3.2-3B-Instruct",
        'GENERATION_MODEL': "Qwen/Qwen2.5-14B-Instruct",
        'SELECTOR_MODEL': "Qwen/Qwen2.5-7B-Instruct"
    },
    'RAW_DATA_FILEPATH': "data/raw",
    'RAW_DATA': "data/raw/arxiv-metadata-oai-snapshot.json",
    'DATA_FILEPATH': "data/processed",
    'DATA_FILETYPE': ".pdf",
    "CONFIDENCE_THRESHOLD": 0.9,
    'YEAR_FILTER': 2024,
    'NUM_DOCUMENTS': 10,
    'LR': 1e-5,
    'JSON_SELECTION_FILEPATH': "data/processed/filtered_results.json",
    'CHUNKING_CHARACTERS': 1000,
    'OVERLAP_CHARACTERS': 200,
    'CSV_FILEPATH': "data/main/data.csv",
    'CHUNKS_FILEPATH': "data/main/chunks.jsonl",
    'DEBUG_FILEPATH': "logs/json/node_tracking.jsonl",
    "VECTOR_DB_DIR": "db/chroma_db",
    "EMBEDDING_MODEL": "BAAI/bge-base-en-v1.5",#BAAI/bge-base-en-v1.5
    "EMBEDDING_DEVICE": "cpu",
    "CHROMA_COLLECTION_METADATA": {"hnsw:space": "cosine"},
    "CLEAR_VECTOR_DB": True, 
    "EVAL_K": 5,
    "GOOD_DATA_CSV": "data/main/sft_good_data.csv",
    "BAD_DATA_CSV": "data/main/sft_bad_data.csv",
    "GOOD_DATA_CSV_WITH_DUP": "data/main/sft_good_data_with_dup.csv",
    "GOOD_DATA_CSV_NO_DUP": "data/main/sft_good_data_no_dup.csv",
    "TRAIN_GOOD_DATA_CSV_WITH_DUP": "data/main/train_good_data_with_dup.csv",
    "TEST_GOOD_DATA_CSV_WITH_DUP": "data/main/test_good_data_with_dup.csv",
    "TEST_SIZE":0.2 , 
    "QR_OUTPUT": "src/pipeline/LlamaFactory/data/qr_sft_data.json",
    "SEL_OUTPUT": "src/pipeline/LlamaFactory/data/sel_sft_data.json",
    "GEN_OUTPUT": "src/pipeline/LlamaFactory/data/gen_sft_data.json",
    "CHUNK_SEP": " ||| "
}